# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FesseMisk CTF
email: fessemisk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  FesseMisk CTF team 
twitter_username: 
github_username: FesseMisk
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin2   : "dark"
search: true
repository: FesseMisk/FesseMisk.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"


# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
remote_theme: mmistakes/minimal-mistakes@4.24.0
url: 'https://www.fessemisk.com' # your main domain
baseurl: '' # if you're using custom domain keep this blank example: baseurl: ''

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "FesseMisk"
  avatar : "https://images.squarespace-cdn.com/content/v1/54a2e8cbe4b08f7628c934c8/1504807920952-7ARNSMPXIS26L9GNKCFU/Puffer-Fish-Avatar-433px.png"
  bio    : "CTF team consisting of students from [Norwegian Defence Cyber Academy](https://www.forsvaret.no/utdanning/utdanninger/ingeniorfag-studieretning-telematikk)"
  location : "Lillehammer, Norge"
  links:
    #- label: "CV"
    #  icon: "fas fa-fw fa-link"
    #  url: ""
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/julian_hal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FesseMisk"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/julianhal"
    #- label: "LinkedIn"
    #  icon: "fab fa-linkedin-in"
    #  url: "https://www.linkedin.com/in/julian-hals%C3%B8y-7233b1145/"

footer:
  links:
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/julian_hal"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/julianhal"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/julianhal"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      author_profile: false
      share: false
      comments: false
      share: true
      read_time: false
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "giscus"
  giscus:
    repo                 : "FesseMisk/FesseMisk.github.io"  
    repo_id              : "R_kgDOH8hrYQ"  # Shown during giscus setup at https://giscus.app
    category_name        : "General" # Full text name of the category
    category_id          : "DIC_kwDOH8hrYc4CRQSb"  # Shown during giscus setup at https://giscus.app
    discussion_term      : "url" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : "1" # '1' for enabled (default), '0' for disabled
    theme                : "transparent_dark"  # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

collections:
  docs:
    output: true
    permalink: /:collection/:path/


#analytics:
  #provider: "google-gtag"
  #google:
    #tracking_id: "G-9JHZYDNF5S"
    #anonymize_ip: false # default
